###
# Signup component
###

kind: Deployment
apiVersion: apps/v1
metadata:
  labels:
    cluster: management
    component: signup
  name: signup
  namespace: nalej
spec:
  replicas: 1
  revisionHistoryLimit: 10
  selector:
    matchLabels:
      cluster: management
      component: signup
  template:
    metadata:
      labels:
        cluster: management
        component: signup
    spec:
      containers:
      - name: signup
        image: nalejregistry.azurecr.io/nalej/signup:VERSION
        imagePullPolicy: IfNotPresent
        args:
        - "run"
        - "--debug"
        - "--systemModelAddress=system-model.nalej:8800"
        - "--userManagerAddress=user-manager.nalej:8920"
        securityContext:
          runAsUser: 2000
      imagePullSecrets:
      - name: nalej-registry
