###
# Signup component
###

kind: Deployment
apiVersion: apps/v1
metadata:
  labels:
    cluster: management
    component: signup
  name: signup
  namespace: nalej
spec:
  replicas: 1
  revisionHistoryLimit: 10
  selector:
    matchLabels:
      cluster: management
      component: signup
  template:
    metadata:
      labels:
        cluster: management
        component: signup
    spec:
      containers:
      - name: signup
        image: nalejregistry.azurecr.io/nalej/signup:VERSION
        imagePullPolicy: IfNotPresent
        args:
        - "run"
        - "--debug"
        - "--systemModelAddress=system-model.nalej:8800"
        - "--userManagerAddress=user-manager.nalej:8920"
        - "--usePresharedSecret"
        #- "--tls"
        #- "--caPath=/var/run/secrets/kubernetes.io/serviceaccount/ca.crt"
        #- "--certFilePath=/etc/signup/server/signup.crt"
        #- "--certKeyPath=/etc/signup/server/signup.key"
        #- "--clientSecretPath=/etc/signup/client/secret"
        securityContext:
          runAsUser: 2000
        volumeMounts:
        - name: signup-server-tls-volume
          mountPath: "/etc/signup/server"
          readOnly: true
        - name: signup-client-secret-volume
          mountPath: "/etc/signup/client"
          readOnly: true
      imagePullSecrets:
      - name: nalej-registry
      volumes:
      - name: signup-server-tls-volume
        secret:
          secretName: signup-server-tls
      - name: signup-client-secret-volume
        secret:
          secretName: signup-client-secret
