kind: Service
apiVersion: v1
metadata:
  name: signup
  labels:
    cluster: management
    component: signup
  namespace: __NPH_NAMESPACE
spec:
  selector:
    cluster: management
    component: signup
  type: ClusterIP
  ports:
  - protocol: TCP
    port: 8180
    targetPort: 8180
