###
# Signup component
###

kind: Deployment
apiVersion: apps/v1
metadata:
  labels:
    cluster: management
    component: signup
  name: signup
  namespace: __NPH_NAMESPACE
spec:
  replicas: 1
  revisionHistoryLimit: 10
  selector:
    matchLabels:
      cluster: management
      component: signup
  template:
    metadata:
      labels:
        cluster: management
        component: signup
    spec:
      containers:
        - name: signup
          image: __NPH_REGISTRY_NAMESPACE/signup:__NPH_VERSION
          imagePullPolicy: Always
          args:
            - "run"
            - "--systemModelAddress=system-model.__NPH_NAMESPACE:8800"
            - "--userManagerAddress=user-manager.__NPH_NAMESPACE:8920"
            - "--usePresharedSecret"
          #- "--tls"
          #- "--caPath=/var/run/secrets/kubernetes.io/serviceaccount/ca.crt"
          #- "--certFilePath=/etc/signup/server/signup.crt"
          #- "--certKeyPath=/etc/signup/server/signup.key"
          #- "--clientSecretPath=/etc/signup/client/secret"
          securityContext:
            runAsUser: 2000
          #volumeMounts:
          #- name: signup-server-tls-volume
          #  mountPath: "/etc/signup/server"
          #  readOnly: true
          #- name: signup-client-secret-volume
          #  mountPath: "/etc/signup/client"
          #  readOnly: true
      #volumes:
      #- name: signup-server-tls-volume
      #  secret:
      #    secretName: signup-server-tls
      #- name: signup-client-secret-volume
      #  secret:
      #    secretName: signup-client-secret
